
name: edulist_app
description: EduList Flutter App
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1

flutter:
  uses-material-design: true
